language: node_js
node_js:
- '10.8'
cache:
  directories:
  - "$HOME/.npm"
before_install:
- npm i -g yarn
- yarn
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
script: npm test

notifications:
  slack:
    secure: jmiuZope73X+2S63X+eqlhVy5ot9/dOAXMq5m5dyHDSmkRh1XfUNwpZZWmdtJfdEoU/S6TsXfPmlfY65OY8NbYcITnqk62hFMhO0N+P7+S00bBqliTFu3E/VkKR3nYTqPZsNRBaRJZlsSd9ai+2ceGCDmZLQTS9B3PpAqJB6NwQmUevaHAS1Dz75iIVugB2C3z+22SG9lydAaLmVs3avWvTvP6HXulF2F6R8DfTHGDnYyJhQpkwhO8fgsXnggnyMN1qHkSkVXdTBz/mizP363/oV49zWN4hLPSGcBNL+CNhTuhjgvZ3KJrB1aQ0eey4zrBjSWDR+GJH+M/vY+mmM6d43oaX5imY7HpUgvPykyYJ0ha1ZmTA6GvBGCcK+20v+4fpVk1hcRHV53yq5PyJV7OA8KFQGcj38noP/3a6CtBHGf5Y3a5bFHXZGoFMIy1aly9PgNXaGsv+wTIAWetVuRd0gJjz6zPOsfVXayDc+vygzhYv0uj+VROQyttoRUaY2T+WLi1OPIFhdfEMf/n0Du6eviHSi/hA6pON0ngaqbx9dopiKeSfjzJwPu1Bl3TMoYsyRRJlN2bMVHKq8w8OudHtqB4QDLiAAt4GuP7Qe9d5bbZZmNq6h1i3Tbk/4aM4YcF8lULhIFT4EiZYADKEUpMOQbIhdk9VOSwQZypL7zFQ=
